R, T = "router.py", "train.py"
M = [
 (R, "sin aviso de que no es un diagnóstico", "no es un diagnóstico y no reemplaza", "y no reemplaza"),
 (R, "sin aviso de puntajes no calibrados", "Los puntajes no son probabilidades calibradas. ", ""),
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "límite de edad ge=-5", "age: int = Field(ge=18,", "age: int = Field(ge=-5,"),
 (R, "límite AST le=4000", "ast: float = Field(ge=5, le=400,", "ast: float = Field(ge=5, le=4000,"),
 (R, "límite creatinina le=100000", "crea: float = Field(ge=5, le=1200,", "crea: float = Field(ge=5, le=100000,"),
 (R, "sin aviso de rango", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if False:"),
 (R, "sexo sin restricción", 'sex: Literal["f", "m"]', "sex: str"),
 (R, "puntaje mal calculado en el texto", "round(puntajes[c] * 100)", "round(puntajes[c] * 10)"),
 (R, "sin leyenda de donante sano", '" (sin signos de enfermedad hepática en estos datos)" if clase == "donante" else ""', '""'),
 (R, "clase distinta de la del modelo", "clase, puntajes = predecir_con_pipeline(", "_, puntajes = predecir_con_pipeline("),
 (T, "ORDEN de las clases invertido", 'ORDEN = ["donante", "hepatitis", "fibrosis", "cirrosis"]', 'ORDEN = ["cirrosis", "fibrosis", "hepatitis", "donante"]'),
 (T, "ENFERMEDAD sin hepatitis", 'ENFERMEDAD = ["hepatitis", "fibrosis", "cirrosis"]', 'ENFERMEDAD = ["fibrosis", "cirrosis"]'),
 (T, "F1 micro en lugar de macro", 'f1_score(y, pred, labels=ORDEN, average="macro", zero_division=0)', 'f1_score(y, pred, labels=ORDEN, average="micro", zero_division=0)'),
 (T, "especificidad mal calculada", '"especificidad": round(float((~pred[~real]).mean()), 4)', '"especificidad": round(float((pred[~real]).mean()), 4)'),
 (T, "se conserva la clase sospechosa", 'df = df[df["category"].isin(CLASES)].reset_index(drop=True)', 'df = df.reset_index(drop=True)\n    df["category"] = df["category"].replace({"0s=suspect Blood Donor": "0=Blood Donor"})'),
 (T, "LR sin ponderar", 'LogisticRegression(max_iter=5000, class_weight="balanced")),\n        "k vecinos"', 'LogisticRegression(max_iter=5000)),\n        "k vecinos"'),
 (T, "RF sin ponderar", 'class_weight="balanced_subsample", random_state=SEMILLA, n_jobs=-1), escalar=False),', 'random_state=SEMILLA, n_jobs=-1), escalar=False),'),
 (T, "imputación con la media", 'SimpleImputer(strategy="median")', 'SimpleImputer(strategy="mean")'),
 (T, "partición sin estratificar", "test_size=0.2, stratify=df[OBJETIVO], random_state=SEMILLA)", "test_size=0.2, random_state=SEMILLA)"),
 (T, "ganador = el peor", "ganador = max((n for n in comparacion", "ganador = min((n for n in comparacion"),
 (T, "ALP entra al modelo", "VARIABLES = NUMERICAS + CATEGORICAS", 'VARIABLES = NUMERICAS + CATEGORICAS + ["alp"]'),
 (T, "rango de TODO el dataset", 'rango": {c: [float(X_train[c].min()), float(X_train[c].max())] for c in NUMERICAS}', 'rango": {c: [float(df[c].min()), float(df[c].max())] for c in NUMERICAS}'),
 (T, "bootstrap del F1 con la exactitud", '"f1_macro": intervalo_bootstrap(np.asarray(y_test), pred, f1_macro_de),', '"f1_macro": intervalo_bootstrap(np.asarray(y_test), pred, lambda y, p: float((y == p).mean())),'),
 (T, "predicciones fuera de muestra sin mezclar", "cv=StratifiedKFold(5, shuffle=True, random_state=SEMILLA))\n    metricas[\"oof_entrenamiento\"]", "cv=StratifiedKFold(5))\n    metricas[\"oof_entrenamiento\"]"),
 (T, "kNN con 1 vecino", "KNeighborsClassifier(n_neighbors=5,", "KNeighborsClassifier(n_neighbors=1,"),
 (T, "ajuste final con entrenamiento+prueba", "pipeline = candidatos()[ganador].fit(X_train, y_train)\n", "pipeline = candidatos()[ganador].fit(df[VARIABLES], df[OBJETIVO])\n"),
]
