R, T, Z = "router.py", "train.py", "razon.py"
# Mutantes equivalentes (se declaran): "se puede elegir la línea base" (nunca tiene el menor RMSE) y "selección con R2" (el bosque de razón también
# gana por R2). El recorte a cero se prueba con un caso real (la razón predicha nunca es negativa), no con una mutación.
M = [
 # --- razon.py ---
 (Z, "razón multiplicada en el ajuste", 'razon = np.asarray(y, dtype=float) / X["present_price"].to_numpy(dtype=float)', 'razon = np.asarray(y, dtype=float) * X["present_price"].to_numpy(dtype=float)'),
 (Z, "predicción sin multiplicar por el precio de agencia", ' * X["present_price"].to_numpy(dtype=float)\n', "\n"),
 (Z, "logaritmo ignorado al predecir", "(np.exp(razon) if self.log else razon)", "razon"),
 (Z, "logaritmo ignorado al ajustar", "np.log(razon) if self.log else razon", "razon"),
 (Z, "el modelo no se clona", "clone(self.modelo).fit(X,", "self.modelo.fit(X,"),
 # --- router ---
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "año mínimo 1900", "year: int = Field(ge=1990,", "year: int = Field(ge=1900,"),
 (R, "año máximo 2100", "le=2026, description=\"Año", "le=2100, description=\"Año"),
 (R, "precio de agencia puede ser cero", "present_price: float = Field(gt=0,", "present_price: float = Field(ge=0,"),
 (R, "precio de agencia máximo 1500", "gt=0, le=150,", "gt=0, le=1500,"),
 (R, "kilometraje máximo 10 millones", "le=1_000_000", "le=10_000_000"),
 (R, "kilometraje negativo", "kms_driven: int = Field(ge=0,", "kms_driven: int = Field(ge=-5,"),
 (R, "dueños máximo 10", "owner: int = Field(ge=0, le=3,", "owner: int = Field(ge=0, le=10,"),
 (R, "sin gas natural", 'Literal["Petrol", "Diesel", "CNG"]', 'Literal["Petrol", "Diesel"]'),
 (R, "vendedor libre", 'seller_type: Literal["Dealer", "Individual"]', "seller_type: str"),
 (R, "transmisión libre", 'transmission: Literal["Manual", "Automatic"]', "transmission: str"),
 (R, "descripción del año vacía", 'description="Año de fabricación"', 'description=""'),
 (R, "kilometraje sin unidad", 'description="Kilometraje recorrido (km)"', 'description="Kilometraje recorrido"'),
 (R, "ejemplo fuera de límites", "examples=[2014])", "examples=[1800])"),
 (R, "rupias por lakh", "RUPIAS_POR_LAKH = 100_000", "RUPIAS_POR_LAKH = 10_000"),
 (R, "dueños raros desde 3", "DUENOS_RAROS = 2", "DUENOS_RAROS = 3"),
 (R, "dueños raros desde 1", "DUENOS_RAROS = 2", "DUENOS_RAROS = 1"),
 (R, "sin aviso de gas natural", 'if entrada.fuel_type == "CNG" or entrada.owner >= DUENOS_RAROS:', "if entrada.owner >= DUENOS_RAROS:"),
 (R, "sin aviso de dueños", 'if entrada.fuel_type == "CNG" or entrada.owner >= DUENOS_RAROS:', 'if entrada.fuel_type == "CNG":'),
 (R, "sin aviso de rango", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if False:"),
 (R, "aviso de rango siempre", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if True:"),
 (R, "margen del aviso 0", 'fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos)', 'fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos, margen=0.0)'),
 (R, "margen del aviso 15 %", 'fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos)', 'fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos, margen=0.15)'),
 (R, "porcentaje mal calculado", "round(valor / entrada.present_price * 100)", "round(valor / 100)"),
 (R, "un decimal", "round(max(valor, 0.0), 2)", "round(max(valor, 0.0), 1)"),
 (R, "sin redondear", "round(max(valor, 0.0), 2)", "max(valor, 0.0)"),
 (R, "texto sin rupias", "unas {formato(valor * RUPIAS_POR_LAKH)} rupias, ", ""),
 (R, "texto sin porcentaje", "alrededor del {porcentaje} por ciento de su precio de agencia.", "."),
 (R, "sin atención por rango", "Atención: el año, el kilometraje", "Nota: el año, el kilometraje"),
 (R, "formato sin separador", 'return f"{numero:,.0f}".replace(",", " ")', 'return f"{numero:.0f}"'),
 (R, "unidad distinta", '"unidad": "lakhs INR"', '"unidad": "INR"'),
 (R, "comandos vacíos", '"comandos": ["precio de un auto", "precio de un carro", "cuanto vale mi carro"],', '"comandos": [],'),
 # --- train ---
 (T, "no se quitan duplicados", "return df.drop_duplicates().reset_index(drop=True) if quitar_duplicados else df", "return df"),
 (T, "car_name entra", 'df = df.drop(columns=["car_name"])', "df = df.drop(columns=[])"),
 (T, "semilla distinta", "SEMILLA = 42", "SEMILLA = 7"),
 (T, "prueba del 30 %", "test_size=0.2, random_state=SEMILLA)", "test_size=0.3, random_state=SEMILLA)"),
 (T, "línea base de la media con la mediana", 'armar(DummyRegressor(strategy="mean")),\n        "regla', 'armar(DummyRegressor(strategy="median")),\n        "regla'),
 (T, "regla de depreciación con la media", 'RazonAlPrecioActual(armar(DummyRegressor(strategy="median")))', 'RazonAlPrecioActual(armar(DummyRegressor(strategy="mean")))'),
 (T, "log-razón sin logaritmo", "RazonAlPrecioActual(armar(LinearRegression()), log=True)", "RazonAlPrecioActual(armar(LinearRegression()))"),
 (T, "regresión lineal en razón", '"regresión lineal": armar(LinearRegression()),', '"regresión lineal": RazonAlPrecioActual(armar(LinearRegression())),'),
 (T, "bosque pequeño", "n_estimators=200, random_state=SEMILLA, n_jobs=-1", "n_estimators=10, random_state=SEMILLA, n_jobs=-1"),
 (T, "boosting con parada temprana", "early_stopping=False,", "early_stopping=True,"),
 (T, "boosting con otra tasa", "learning_rate=0.05", "learning_rate=0.5"),
 (T, "sin estandarizar", '("num", StandardScaler(), NUMERICAS)', '("num", "passthrough", NUMERICAS)'),
 (T, "categóricas sin ignorar desconocidas", 'OneHotEncoder(handle_unknown="ignore")', "OneHotEncoder()"),
 (T, "una repetición de validación", "RepeatedKFold(n_splits=5, n_repeats=3,", "RepeatedKFold(n_splits=5, n_repeats=1,"),
 (T, "3 pliegues de validación", "RepeatedKFold(n_splits=5, n_repeats=3,", "RepeatedKFold(n_splits=3, n_repeats=3,"),
 (T, "se elige el peor", "ganador = min(", "ganador = max("),
 (T, "se puede elegir la línea base", "for n in comparacion if not es_linea_base(n)), key", "for n in comparacion), key"),
 (T, "selección con R2", 'key=lambda n: comparacion[n]["cv_rmse"])', 'key=lambda n: -comparacion[n]["cv_r2"])'),
 (T, "selección con la prueba", "r = cross_validate(pipe, X_train, y_train,", "r = cross_validate(pipe, df[VARIABLES], df[OBJETIVO],"),
 (T, "línea base de la media con la regla", 'candidatos()["precio medio (línea base)"].fit(X_train, y_train).predict(X_test))', 'candidatos()["regla de depreciación (línea base)"].fit(X_train, y_train).predict(X_test))'),
 (T, "IC con menos remuestreos de otra métrica", '"mae": intervalo_bootstrap(y, p, lambda a, b: float(mean_absolute_error(a, b))),', '"mae": intervalo_bootstrap(y, p, lambda a, b: float(mean_squared_error(a, b))),'),
 (T, "precio alto 30", "PRECIO_ALTO = 15", "PRECIO_ALTO = 30"),
 (T, "extrapolación con el modelo equivocado", 'for nombre in ("random forest", ganador):', 'for nombre in ("gradient boosting", ganador):'),
 (T, "rango de entrenamiento y no de todos", '{c: [float(df[c].min()), float(df[c].max())] for c in CON_RANGO}', '{c: [float(X_train[c].min()), float(X_train[c].max())] for c in CON_RANGO}'),
 (T, "ejemplo del entrenamiento", 'X_test.iloc[[0]].to_dict("records")[0]', 'X_train.iloc[[0]].to_dict("records")[0]'),
 (T, "modelo final solo con entrenamiento", "final = candidatos()[ganador].fit(df[VARIABLES], df[OBJETIVO])", "final = candidatos()[ganador].fit(X_train, y_train)"),
 (T, "rango con el dueño", 'CON_RANGO = ["year", "present_price", "kms_driven"]', 'CON_RANGO = ["year", "present_price", "kms_driven", "owner"]'),
 (T, "artefacto sin marca de reentrenado", "reentrenado_con_todo=True", "reentrenado_con_todo=False"),
 (T, "main sin entender", "    entender(df, len(crudo))\n", ""),
 (T, "entender cuenta mal", "Filas crudas: {n_crudo}  Filas sin duplicados: {len(df)}", "Filas crudas: {len(df)}  Filas sin duplicados: {n_crudo}"),
 (T, "razón con otra mediana", "razon.median():.2f", "razon.mean():.2f"),
 (T, "pureza: entrenar escribe las figuras", "metricas = evaluar(modelo, X_test, y_test, figuras)", 'metricas = evaluar(modelo, X_test, y_test, figuras or CARPETA / "figuras")'),
]
