R, T = "router.py", "train.py"
M = [
 (R, "clase con umbral 0.5", 'clase = "Yes" if p >= artefacto["umbral"] else "No"', 'clase = "Yes" if p >= 0.5 else "No"'),
 (R, "sin nivel moderado", 'nivel = "alto" if p >= artefacto["umbral"] else "moderado" if p >= artefacto["umbral_sensibilidad"] else "bajo"', 'nivel = "alto" if p >= artefacto["umbral"] else "bajo"'),
 (R, "nivel moderado con el umbral equivocado", '"moderado" if p >= artefacto["umbral_sensibilidad"] else "bajo"', '"moderado" if p >= artefacto["umbral"] / 2 else "bajo"'),
 (R, "niveles invertidos", 'nivel = "alto" if p >= artefacto["umbral"] else', 'nivel = "bajo" if p >= artefacto["umbral"] else'),
 (R, "porcentaje mal calculado", "porcentaje = round(p * 100, 1)", "porcentaje = round(p * 10, 1)"),
 (R, "sin aviso médico", "lo que corresponde a un riesgo {nivel}. {AVISO}", "lo que corresponde a un riesgo {nivel}."),
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "límite de edad le=12000", "age: float = Field(ge=0, le=120,", "age: float = Field(ge=0, le=12000,"),
 (R, "límite de glucosa ge=-5", "avg_glucose_level: float = Field(ge=40,", "avg_glucose_level: float = Field(ge=-5,"),
 (R, "sin aviso de rango", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if False:"),
 (R, "hipertensión sin restricción", 'hypertension: Literal["Yes", "No"]', "hypertension: str"),
 (T, "ORDEN invertido", 'POSITIVO, ORDEN = "Yes", ["No", "Yes"]', 'POSITIVO, ORDEN = "Yes", ["Yes", "No"]'),
 (T, "'>=' por '>'", 'pred = np.where(np.asarray(p_yes) >= umbral, POSITIVO, "No")', 'pred = np.where(np.asarray(p_yes) > umbral, POSITIVO, "No")'),
 (T, "umbral F1 calculado con la PRUEBA", "umbral = umbral_optimo_f1(y_oof, oof, rejilla=REJILLA_F1)", "umbral = umbral_optimo_f1((np.asarray(y_test) == POSITIVO).astype(int), pipeline.predict_proba(X_test)[:, 1], rejilla=REJILLA_F1)"),
 (T, "recall objetivo 0.5", "RECALL_OBJETIVO = 0.8", "RECALL_OBJETIVO = 0.5"),
 (T, "rejilla F1 desde 0.05", "REJILLA_F1 = np.round(np.arange(0.01, 0.951, 0.01), 2)", "REJILLA_F1 = np.round(np.arange(0.05, 0.951, 0.01), 2)"),
 (T, "rango de TODO el dataset", 'rango": {c: [float(X_train[c].min()), float(X_train[c].max())] for c in NUMERICAS}', 'rango": {c: [float(df[c].min()), float(df[c].max())] for c in NUMERICAS}'),
 (T, "ganador = el peor", "ganador = max((n for n in comparacion", "ganador = min((n for n in comparacion"),
 (T, "calibración con 3 bins", "n_bins=5", "n_bins=3"),
 (T, "ajuste final con entrenamiento+prueba", "pipeline = candidatos()[ganador].fit(X_train, y_train)\n", "pipeline = candidatos()[ganador].fit(df[VARIABLES], df[OBJETIVO])\n"),
 (T, "imputación con la media", 'SimpleImputer(strategy="median")', 'SimpleImputer(strategy="mean")'),
 (T, "min_samples_leaf=1", "min_samples_leaf=20, max_depth=6", "min_samples_leaf=1, max_depth=6"),
 (T, "bootstrap del AUC con otra métrica", '"roc_auc": intervalo_bootstrap(y_bin, p_yes, roc_auc_score),', '"roc_auc": intervalo_bootstrap(y_bin, p_yes, average_precision_score),'),
 (T, "brier de la tasa base mal calculado", 'round(prevalencia * (1 - prevalencia), 4)', 'round(prevalencia, 4)'),
 (T, "validación cruzada con 2 repeticiones", "RepeatedStratifiedKFold(n_splits=5, n_repeats=4, random_state=SEMILLA)", "RepeatedStratifiedKFold(n_splits=5, n_repeats=2, random_state=SEMILLA)"),
]
