R, T = "router.py", "train.py"
# Mutante equivalente (se declara): "selección con exactitud" (el bosque también gana por exactitud).
M = [
 # --- router ---
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "tipo libre", 'tipo: Literal["red", "white"]', "tipo: str"),
 (R, "acidez fija mínima 0", "fixed_acidity: float = Field(ge=3,", "fixed_acidity: float = Field(ge=0,"),
 (R, "acidez fija máxima 50", "fixed_acidity: float = Field(ge=3, le=17", "fixed_acidity: float = Field(ge=3, le=50"),
 (R, "acidez volátil máxima 9", "volatile_acidity: float = Field(ge=0.05, le=2", "volatile_acidity: float = Field(ge=0.05, le=9"),
 (R, "ácido cítrico máximo 9", "citric_acid: float = Field(ge=0, le=2", "citric_acid: float = Field(ge=0, le=9"),
 (R, "azúcar máximo 700", "residual_sugar: float = Field(ge=0.3, le=70", "residual_sugar: float = Field(ge=0.3, le=700"),
 (R, "cloruros mínimo 0", "chlorides: float = Field(ge=0.005,", "chlorides: float = Field(ge=0,"),
 (R, "azufre libre máximo 3200", "free_sulfur_dioxide: float = Field(ge=0.5, le=320", "free_sulfur_dioxide: float = Field(ge=0.5, le=3200"),
 (R, "azufre total máximo 4600", "total_sulfur_dioxide: float = Field(ge=5, le=460", "total_sulfur_dioxide: float = Field(ge=5, le=4600"),
 (R, "densidad máxima 5", "density: float = Field(ge=0.98, le=1.05", "density: float = Field(ge=0.98, le=5"),
 (R, "pH máximo 14", "ph: float = Field(ge=2.6, le=4.2", "ph: float = Field(ge=2.6, le=14"),
 (R, "sulfatos máximo 9", "sulphates: float = Field(ge=0.2, le=2.1", "sulphates: float = Field(ge=0.2, le=9"),
 (R, "alcohol mínimo 0", "alcohol: float = Field(ge=7.5,", "alcohol: float = Field(ge=0,"),
 (R, "alcohol máximo 40", "alcohol: float = Field(ge=7.5, le=15.5", "alcohol: float = Field(ge=7.5, le=40"),
 (R, "libre puede superar al total", "if self.free_sulfur_dioxide > self.total_sulfur_dioxide:", "if False:"),
 (R, "libre no puede igualar al total", "if self.free_sulfur_dioxide > self.total_sulfur_dioxide:", "if self.free_sulfur_dioxide >= self.total_sulfur_dioxide:"),
 (R, "unidad del azufre sin mg", 'description="Dióxido de azufre libre (mg/dm³)"', 'description="Dióxido de azufre libre"'),
 (R, "descripción vacía del pH", 'description="pH"', 'description=""'),
 (R, "ejemplo fuera de límites", 'description="Grado alcohólico (% vol.)", examples=[10.5]', 'description="Grado alcohólico (% vol.)", examples=[50.5]'),
 (R, "umbral de poco concluyente 0.6", "UMBRAL_POCO_CONCLUYENTE = 0.5", "UMBRAL_POCO_CONCLUYENTE = 0.6"),
 (R, "umbral de poco concluyente 0.4", "UMBRAL_POCO_CONCLUYENTE = 0.5", "UMBRAL_POCO_CONCLUYENTE = 0.4"),
 (R, "sin aviso de poco concluyente", "La clasificación es poco concluyente: ninguna clase supera el 50 por ciento.", ""),
 (R, "sin aviso de rango", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if False:"),
 (R, "aviso de rango siempre", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if True:"),
 (R, "tinto y blanco intercambiados", 'tipo = "tinto" if entrada.tipo == "red" else "blanco"', 'tipo = "blanco" if entrada.tipo == "red" else "tinto"'),
 (R, "porcentajes sin redondear bien", "round(probabilidades[c] * 100)", "round(probabilidades[c] * 10)"),
 (R, "orden de las clases invertido", 'ORDEN = ("baja", "media", "alta")', 'ORDEN = ("alta", "media", "baja")'),
 (R, "probabilidad de otra clase en el texto", "con una probabilidad del {round(probabilidades[clase] * 100)} por ciento", "con una probabilidad del {round(probabilidades['media'] * 100)} por ciento"),
 (R, "comandos vacíos", '"comandos": ["calidad del vino", "clasificar vino", "que tan bueno es el vino"],', '"comandos": [],'),
 (R, "la API devuelve la peor clase", "clase, probabilidades = predecir_con_pipeline(CARPETA, MODELO_INFO[\"slug\"], datos)", "clase, probabilidades = predecir_con_pipeline(CARPETA, MODELO_INFO[\"slug\"], {**datos, \"alcohol\": datos[\"alcohol\"] - 3})"),
 # --- train ---
 (T, "agrupación: 5 es media", "np.where(puntaje <= 5,", "np.where(puntaje <= 4,"),
 (T, "agrupación: 7 es media", 'np.where(puntaje == 6, "media", "alta")', 'np.where(puntaje <= 7, "media", "alta")'),
 (T, "no se quitan duplicados", "df = sin_duplicados(df)", "pass"),
 (T, "partición sin estratificar", "test_size=0.2, stratify=y, random_state=SEMILLA)", "test_size=0.2, random_state=SEMILLA)"),
 (T, "semilla distinta", "SEMILLA = 42", "SEMILLA = 7"),
 (T, "prueba del 30 %", "test_size=0.2, stratify=y, random_state=SEMILLA)", "test_size=0.3, stratify=y, random_state=SEMILLA)"),
 (T, "imputación con la media", 'SimpleImputer(strategy="median")', 'SimpleImputer(strategy="mean")'),
 (T, "variable de menos", '"free_sulfur_dioxide", "total_sulfur_dioxide", "density", "ph", "sulphates", "alcohol",', '"free_sulfur_dioxide", "total_sulfur_dioxide", "density", "ph", "sulphates",'),
 (T, "la puntuación entra al modelo", "VARIABLES = NUMERICAS + CATEGORICAS", 'VARIABLES = NUMERICAS + CATEGORICAS + ["quality"]'),
 (T, "bosque pequeño", "n_estimators=100, min_samples_leaf=5, max_depth=16", "n_estimators=10, min_samples_leaf=5, max_depth=16"),
 (T, "bosque sin ponderar", 'class_weight="balanced_subsample",  # compacto', "class_weight=None,  # compacto"),
 (T, "regresión logística sin ponderar", 'LogisticRegression(max_iter=3000, class_weight="balanced")', "LogisticRegression(max_iter=3000)"),
 (T, "svm con probabilidades", 'SVC(C=3, class_weight="balanced", random_state=SEMILLA)', 'SVC(C=3, class_weight="balanced", probability=True, random_state=SEMILLA)'),
 (T, "svm con C distinto", "SVC(C=3,", "SVC(C=1,"),
 (T, "boosting con parada temprana", "early_stopping=False,", "early_stopping=True,"),
 (T, "validación con una repetición", "RepeatedStratifiedKFold(n_splits=5, n_repeats=2,", "RepeatedStratifiedKFold(n_splits=5, n_repeats=1,"),
 (T, "validación con 3 pliegues", "RepeatedStratifiedKFold(n_splits=5, n_repeats=2,", "RepeatedStratifiedKFold(n_splits=3, n_repeats=2,"),
 (T, "selección con exactitud", 'key=lambda n: comparacion[n]["cv_f1_macro"])', 'key=lambda n: comparacion[n]["cv_accuracy"])'),
 (T, "se elige el peor", "ganador = max(elegibles(),", "ganador = min(elegibles(),"),
 (T, "se puede elegir la línea base", 'if "línea base" not in n and hasattr(pipe, "predict_proba")]', 'if hasattr(pipe, "predict_proba")]'),
 (T, "se puede elegir un modelo sin probabilidades", 'if "línea base" not in n and hasattr(pipe, "predict_proba")]', 'if "línea base" not in n]'),
 (T, "selección con la prueba", 'f1 = cross_val_score(pipe, X_train, y_train, cv=validacion, scoring="f1_macro", n_jobs=-1)', 'f1 = cross_val_score(pipe, df[VARIABLES], df[OBJETIVO], cv=validacion, scoring="f1_macro", n_jobs=-1)'),
 (T, "línea base con boosting", 'base = candidatos()["mayoritaria (línea base)"]', 'base = candidatos()["gradient boosting"]'),
 (T, "experimento sin duplicados", "Xc, yc = crudo[VARIABLES], crudo[OBJETIVO]", "Xc, yc = df[VARIABLES], df[OBJETIVO]"),
 (T, "experimento con otra semilla", "test_size=0.2, stratify=yc, random_state=SEMILLA)", "test_size=0.2, stratify=yc, random_state=1)"),
 (T, "rango de todo el dataset", "float(X_train[c].min()), float(X_train[c].max())", "float(df[c].min()), float(df[c].max())"),
 (T, "ejemplo del entrenamiento", 'X_test.iloc[[0]].to_dict("records")[0]', 'X_train.iloc[[0]].to_dict("records")[0]'),
 (T, "main sin entender", "    entender(df, len(crudo))\n", ""),
 (T, "artefacto sin variables", "variables=VARIABLES, rango=r[\"rango\"])", "rango=r[\"rango\"])"),
 (T, "matriz de confusión sin orden", "metricas_clasificacion(y_test, y_pred, orden=ORDEN)", "metricas_clasificacion(y_test, y_pred)"),
 (T, "entender cuenta mal", "Filas crudas: {n_crudo}  Filas sin duplicados: {len(df)}", "Filas crudas: {len(df)}  Filas sin duplicados: {n_crudo}"),
]
