R, T, P = "router.py", "train.py", "preprocesamiento.py"
# Mutantes equivalentes (se declaran): "se puede elegir la línea base" (nunca tiene el menor RMSE), "tipos laxos" (los campos Literal
# rechazan lo que no sea texto y la fecha tiene su propio validador) "sin recorte a cero" (ver test_ninguna_prediccion_cruda_es_negativa) y "selección con la prueba" (el entrenamiento es un prefijo
# de las filas ordenadas por fecha: los mismos índices dan los mismos datos).
M = [
 # --- router ---
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "fecha laxa (acepta enteros)", 'if not isinstance(valor, (str, date)) or isinstance(valor, bool):', "if False:"),
 (R, "fecha con hora permitida", 'if isinstance(valor, str) and not re.fullmatch(r"\\d{4}-\\d{2}-\\d{2}", valor):', "if False:"),
 (R, "fecha mínima 2000", "ge=date(2015, 1, 1)", "ge=date(2000, 1, 1)"),
 (R, "fecha máxima 2200", "le=date(2100, 12, 31)", "le=date(2200, 12, 31)"),
 (R, "región por defecto Albany", 'region: Literal[REGIONES] = Field("TotalUS"', 'region: Literal[REGIONES] = Field("Albany"'),
 (R, "tipo por defecto orgánico", 'Field("conventional", description', 'Field("organic", description'),
 (R, "fecha por defecto fija", "default_factory=date.today,", "default=date(2017, 9, 15),"),
 (R, "región obligatoria", 'Field("TotalUS", description', 'Field(..., description'),
 (R, "una región menos", '"WestTexNewMexico",\n)', ")"),
 (R, "tipo libre", 'tipo: Literal["conventional", "organic"]', "tipo: str"),
 (R, "sin descripción de la fecha", 'description="Fecha de la estimación, AAAA-MM-DD (por defecto, hoy)"', 'description=""'),
 (R, "sin recorte a cero", "round(max(valor, 0.0), 2)", "round(valor, 2)"),
 (R, "tres decimales", "round(max(valor, 0.0), 2)", "round(max(valor, 0.0), 3)"),
 (R, "días de gracia 30", "DIAS_DE_GRACIA = 60", "DIAS_DE_GRACIA = 30"),
 (R, "días de gracia 90", "DIAS_DE_GRACIA = 60", "DIAS_DE_GRACIA = 90"),
 (R, "el aviso usa >=", "if (entrada.fecha - fecha_max).days > DIAS_DE_GRACIA:", "if (entrada.fecha - fecha_max).days >= DIAS_DE_GRACIA:"),
 (R, "sin aviso de poco confiable", "y es poco confiable.", "y es bueno."),
 (R, "sin mencionar la última fecha", "los datos del modelo llegan hasta el {fecha_en_texto(fecha_max)}; para esta fecha es ", "para esta fecha es "),
 (R, "tipo mal traducido", '"convencional" if entrada.tipo == "conventional" else "orgánico"', '"orgánico" if entrada.tipo == "conventional" else "convencional"'),
 (R, "meses desplazados", '"julio", "agosto"', '"agosto", "julio"'),
 (R, "región mal formateada", 'return re.sub(r"(?<=[a-z])(?=[A-Z])", " ", region)', "return region"),
 (R, "TotalUS con otro nombre", 'return "todo Estados Unidos"', 'return "Estados Unidos"'),
 (R, "unidad distinta", '"unidad": "USD por aguacate"', '"unidad": "USD"'),
 (R, "comandos vacíos", '"comandos": ["precio del aguacate", "precio de aguacate", "cuanto cuesta el aguacate"],', '"comandos": [],'),
 (R, "fecha enviada al modelo desplazada", 'pd.Timestamp(entrada.fecha)', "pd.Timestamp(entrada.fecha) + pd.Timedelta(days=30)"),
 # --- preprocesamiento ---
 (P, "semana ISO en lugar del día del año", '"semana": np.minimum((fechas.dt.dayofyear - 1) // 7 + 1, 52).to_numpy(),', '"semana": fechas.dt.isocalendar().week.to_numpy(),'),
 (P, "la semana puede llegar a 53", "np.minimum((fechas.dt.dayofyear - 1) // 7 + 1, 52)", "((fechas.dt.dayofyear - 1) // 7 + 1)"),
 (P, "t sin truncar", 'np.minimum(self._anios(fechas).to_numpy(), self.t_max_)', "self._anios(fechas).to_numpy()"),
 (P, "t en días", "(fechas - INICIO).dt.days / 365.25", "(fechas - INICIO).dt.days"),
 (P, "inicio distinto", 'INICIO = pd.Timestamp("2015-01-04")', 'INICIO = pd.Timestamp("2015-06-04")'),
 (P, "mes sin extraer", '"mes": fechas.dt.month.to_numpy(),', '"mes": fechas.dt.dayofweek.to_numpy(),'),
 (P, "t_max con el mínimo", "self.t_max_ = float(self._anios(pd.to_datetime(X[\"fecha\"])).max())", "self.t_max_ = float(self._anios(pd.to_datetime(X[\"fecha\"])).min())"),
 # --- train ---
 (T, "fracción de prueba 30 %", "FRACCION_PRUEBA = 0.20", "FRACCION_PRUEBA = 0.30"),
 (T, "pliegues de 10 semanas", "SEMANAS_CV = 20", "SEMANAS_CV = 10"),
 (T, "partición incluye el corte en el entrenamiento", "df[df.fecha < corte].reset_index(drop=True)", "df[df.fecha <= corte].reset_index(drop=True)"),
 (T, "partición al azar de filas", "fechas = np.sort(df.fecha.unique())\n    corte", "fechas = np.sort(df.fecha.unique())[::-1]\n    corte"),
 (T, "orden de las filas sin ordenar", '.sort_values(["fecha", "region", "tipo"]).reset_index(drop=True)', ".reset_index(drop=True)"),
 (T, "pliegues sin agrupar por semana", "np.flatnonzero(df_train.fecha.isin(fechas[entrena]))", "np.flatnonzero(df_train.fecha.isin(fechas[entrena][::2]))"),
 (T, "3 pliegues por 2", "def cv_por_semanas(df_train: pd.DataFrame, n_splits: int = 3)", "def cv_por_semanas(df_train: pd.DataFrame, n_splits: int = 2)"),
 (T, "boosting con parada temprana", "early_stopping=False,", "early_stopping=True,"),
 (T, "bosque más pequeño", "n_estimators=100, min_samples_leaf=10, max_depth=14", "n_estimators=10, min_samples_leaf=10, max_depth=14"),
 (T, "ridge sin escalar la tendencia", 'armar(ridge(), grupo + ["mes"], ["t"], StandardScaler())', 'armar(ridge(), grupo + ["mes"], ["t"])'),
 (T, "se elige el peor", "ganador = min(", "ganador = max("),
 (T, "se puede elegir la línea base", 'for n in comparacion if "línea base" not in n), key', "for n in comparacion), key"),
 (T, "selección con la prueba", "r2 = cross_val_score(pipe, train[VARIABLES], train[OBJETIVO], cv=pliegues, scoring=\"r2\")", "r2 = cross_val_score(pipe, df[VARIABLES], df[OBJETIVO], cv=pliegues, scoring=\"r2\")"),
 (T, "línea base con boosting", 'base = candidatos()["efecto región y tipo (línea base)"]', 'base = candidatos()["gradient boosting"]'),
 (T, "modelo final solo con entrenamiento", "final = candidatos()[ganador].fit(df[VARIABLES], df[OBJETIVO])", "final = candidatos()[ganador].fit(train[VARIABLES], train[OBJETIVO])"),
 (T, "fecha máxima del inicio", '"fecha_max": str(df.fecha.max().date())', '"fecha_max": str(df.fecha.min().date())'),
 (T, "ejemplo con otra región", '"entrada_ejemplo": {"region": "TotalUS"', '"entrada_ejemplo": {"region": "Boston"'),
 (T, "artefacto sin marca de reentrenado", "reentrenado_con_todo=True", "reentrenado_con_todo=False"),
 (T, "main sin entender", "    entender(df)\n    train, test, corte", "    train, test, corte"),
 (T, "entender cuenta mal", "Semanas: {df.fecha.nunique()}", "Semanas: {df.region.nunique()}"),
]
