# Mutantes equivalentes (mismo comportamiento con estos datos, se declaran): "se puede elegir la línea base" (la media nunca tiene el menor RMSE)
# y "selección con R2" (Lasso gana también por R2).
R, T = "router.py", "train.py"
M = [
 # --- router ---
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "edad como número decimal", "age: int = Field(", "age: float = Field("),
 (R, "edad mínima 5", "age: int = Field(ge=18,", "age: int = Field(ge=5,"),
 (R, "edad máxima 200", "le=90, description=\"Edad", "le=200, description=\"Edad"),
 (R, "peso mínimo 10", "weight_kg: float = Field(ge=45,", "weight_kg: float = Field(ge=10,"),
 (R, "peso máximo 500", "weight_kg: float = Field(ge=45, le=180", "weight_kg: float = Field(ge=45, le=500"),
 (R, "estatura mínima 50", "height_cm: float = Field(ge=145,", "height_cm: float = Field(ge=50,"),
 (R, "abdomen máximo 500", "abdomen_cm: float = Field(ge=65, le=155", "abdomen_cm: float = Field(ge=65, le=500"),
 (R, "muñeca mínima 1", "wrist_cm: float = Field(ge=14,", "wrist_cm: float = Field(ge=1,"),
 (R, "cuello máximo 99", "neck_cm: float = Field(ge=28, le=55", "neck_cm: float = Field(ge=28, le=99"),
 (R, "campo con descripción vacía", 'description="Circunferencia de la muñeca (cm)"', 'description=""'),
 (R, "peso sin unidad", 'description="Peso en kg"', 'description="Peso"'),
 (R, "ejemplo de peso fuera de límites", "examples=[80.0])", "examples=[800.0])"),
 (R, "sin aviso de rango", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if False:"),
 (R, "aviso siempre", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if True:"),
 (R, "sin recorte a cero", "round(max(valor, 0.0), 1)", "round(valor, 1)"),
 (R, "dos decimales", "round(max(valor, 0.0), 1)", "round(max(valor, 0.0), 2)"),
 (R, "unidad distinta", '"unidad": "%"', '"unidad": "pct"'),
 (R, "comandos vacíos", '"comandos": ["grasa corporal", "masa corporal", "porcentaje de grasa"],', '"comandos": [],'),
 (R, "sin aviso de orientativa", "Es una estimación orientativa, calculada con datos de hombres adultos.", ""),
 (R, "sin aclarar hombres adultos", "calculada con datos de hombres adultos.", "calculada con datos."),
 (R, "sin texto de poco confiable", "el resultado es poco confiable.", "el resultado es bueno."),
 (R, "el router altera la edad", "datos = entrada.model_dump()", 'datos = {**entrada.model_dump(), "age": entrada.age + 1}'),
 (R, "el slug cambia", '"slug": "grasa_corporal"', '"slug": "grasa"'),
 # --- train ---
 (T, "libras a kg incorrecto", "LB_A_KG = 0.45359237", "LB_A_KG = 0.5"),
 (T, "pulgadas a cm incorrecto", "PULGADA_A_CM = 2.54", "PULGADA_A_CM = 2.5"),
 (T, "no se descarta la grasa 0 %", "(df[OBJETIVO] <= 0) | (df[\"height_cm\"] < 120)", "(df[OBJETIVO] < 0) | (df[\"height_cm\"] < 120)"),
 (T, "no se descarta la estatura imposible", "(df[OBJETIVO] <= 0) | (df[\"height_cm\"] < 120)", "(df[OBJETIVO] <= 0) | (df[\"height_cm\"] < 50)"),
 (T, "se descartan más registros", "(df[\"height_cm\"] < 120)", "(df[\"height_cm\"] < 170)"),
 (T, "density entra al modelo", '"thigh_cm", "knee_cm", "ankle_cm", "biceps_cm", "forearm_cm", "wrist_cm",\n]', '"thigh_cm", "knee_cm", "ankle_cm", "biceps_cm", "forearm_cm", "wrist_cm", "density",\n]'),
 (T, "variable de menos", '"age", "weight_kg", "height_cm",', '"age", "weight_kg",'),
 (T, "semilla distinta", "SEMILLA = 42", "SEMILLA = 7"),
 (T, "prueba del 30 %", "test_size=0.2, random_state=SEMILLA)", "test_size=0.3, random_state=SEMILLA)"),
 (T, "linear sin estandarizar", 'return Pipeline([("escala", StandardScaler()), ("modelo", estimador)])', 'return Pipeline([("escala", "passthrough"), ("modelo", estimador)])'),
 (T, "ridge con rejilla corta", "np.logspace(-2, 3, 30)", "np.logspace(-2, 0, 3)"),
 (T, "lasso con 3 pliegues internos", "LassoCV(cv=5,", "LassoCV(cv=3,"),
 (T, "bosque pequeño", "n_estimators=300, min_samples_leaf=2", "n_estimators=10, min_samples_leaf=2"),
 (T, "bosque con hojas de 1", "n_estimators=300, min_samples_leaf=2", "n_estimators=300, min_samples_leaf=1"),
 (T, "validación con una repetición", "RepeatedKFold(n_splits=5, n_repeats=3,", "RepeatedKFold(n_splits=5, n_repeats=1,"),
 (T, "validación con 3 pliegues", "RepeatedKFold(n_splits=5, n_repeats=3,", "RepeatedKFold(n_splits=3, n_repeats=3,"),
 (T, "se elige el peor", "ganador = min(", "ganador = max("),
 (T, "se puede elegir la línea base", 'for n in comparacion if "línea base" not in n), key', "for n in comparacion), key"),
 (T, "selección con R2", 'key=lambda n: comparacion[n]["cv_rmse"])', 'key=lambda n: -comparacion[n]["cv_r2"])'),
 (T, "selección con la prueba", "cross_val_score(pipe, X_train, y_train, cv=validacion, scoring=\"neg_root_mean_squared_error\")", "cross_val_score(pipe, X, y, cv=validacion, scoring=\"neg_root_mean_squared_error\")"),
 (T, "línea base con regresión lineal", 'candidatos()["media (línea base)"].fit(X_train, y_train).predict(X_test))', 'candidatos()["regresión lineal"].fit(X_train, y_train).predict(X_test))'),
 (T, "experimento de fuga con otra métrica", 'metricas_regresion(y_test, fuga.predict(Xd_test))["r2"]', 'metricas_regresion(y_test, fuga.predict(Xd_test))["mae"]'),
 (T, "rango de todo el dataset", 'float(X_train[c].min()), float(X_train[c].max())', 'float(X[c].min()), float(X[c].max())'),
 (T, "ejemplo de entrada del entrenamiento", 'X_test.iloc[[0]].to_dict("records")[0]', 'X_train.iloc[[0]].to_dict("records")[0]'),
 (T, "main sin limpiar", "df = limpiar(cargar_datos())", "df = cargar_datos()"),
 (T, "main sin entender", "    entender(df)\n    explorar(df, figuras)\n    r = entrenar", "    explorar(df, figuras)\n    r = entrenar"),
 (T, "artefacto sin variables", "variables=VARIABLES, rango=r[\"rango\"])", "rango=r[\"rango\"])"),
 (T, "limpiar no informa", 'print(f"Registros imposibles descartados', 'print(f"Descartados'),
 (T, "entender cuenta mal", 'print(f"Filas: {len(df)}  Columnas: {df.shape[1]}")', 'print(f"Filas: {len(df)}  Columnas: {df.shape[0]}")'),
 # --- añadidas tras la verificación independiente del PR de seguimiento ---
 (T, "entrenar escribe las figuras", "metricas = evaluar(pipeline, X_test, y_test, figuras)", 'metricas = evaluar(pipeline, X_test, y_test, figuras or CARPETA / "figuras")'),
 (R, "margen del aviso 0", 'fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos)', 'fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos, margen=0.0)'),
 (R, "margen del aviso 15 %", 'fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos)', 'fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos, margen=0.15)'),
 (R, "rodilla con tipos laxos", "knee_cm: float = Field(ge=30,", "knee_cm: float = Field(strict=False, ge=30,"),
 (R, "texto sin por ciento", "es {valor} por ciento.", "es {valor} unidades."),
 (R, "aviso sin Atención", "Atención: alguna medida", "Nota: alguna medida"),
]
