R, T, S = "router.py", "train.py", "serie.py"
M = [
 # --- router ---
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "mínimo de días 0", "Field(1, ge=1, le=MAX_DIAS", "Field(1, ge=0, le=MAX_DIAS"),
 (R, "máximo de días 8", "MAX_DIAS = 7", "MAX_DIAS = 8"),
 (R, "valor por defecto 2", "Field(1, ge=1", "Field(2, ge=1"),
 (R, "campo dias obligatorio", "Field(1, ge=1", "Field(..., ge=1"),
 (R, "símbolo por defecto MSFT", 'Field("AAPL", description', 'Field("MSFT", description'),
 (R, "símbolo obligatorio", 'Field("AAPL", description', 'Field(..., description'),
 (R, "símbolo libre", "simbolo: Literal[SIMBOLOS]", "simbolo: str"),
 (R, "un símbolo menos", 'SIMBOLOS = ("AAPL", "MSFT", "AMZN", "GOOGL")', 'SIMBOLOS = ("AAPL", "MSFT", "AMZN")'),
 (R, "símbolo mal ligado: sigma de otro", 'artefacto["sigma"][simbolo]', 'artefacto["sigma"]["AAPL"]'),
 (R, "símbolo mal ligado: cierres de otro", 'artefacto["ultimos_cierres"][simbolo]', 'artefacto["ultimos_cierres"]["AAPL"]'),
 (R, "nombre de empresa equivocado", '"MSFT": "Microsoft"', '"MSFT": "Apple"'),
 (R, "alias de Google a Apple", '"google": "GOOGL"', '"google": "AAPL"'),
 (R, "sin alias alphabet", ', "alphabet": "GOOGL"', ""),
 (R, "z del intervalo 1.64", "Z95 = 1.96", "Z95 = 1.64"),
 (R, "sin raíz en el intervalo", "np.sqrt(dias)", "dias"),
 (R, "fecha destino = fecha del último dato", "destino = fecha_destino(ultimo, dias)", "destino = ultimo"),
 (R, "fecha destino en días naturales", "np.busday_offset(np.datetime64(ultimo), dias, roll=\"backward\")", "np.datetime64(ultimo) + dias"),
 (R, "fecha destino con un día de más", "np.busday_offset(np.datetime64(ultimo), dias,", "np.busday_offset(np.datetime64(ultimo), dias + 1,"),
 (R, "predice un día menos", "[artefacto[\"ultimos_cierres\"][simbolo]], dias)[0, -1]", "[artefacto[\"ultimos_cierres\"][simbolo]], dias)[0, 0]"),
 (R, "predice siempre un día", "[artefacto[\"ultimos_cierres\"][simbolo]], dias)", "[artefacto[\"ultimos_cierres\"][simbolo]], 1)"),
 (R, "redondeo a enteros", "valor = round(valor, 2)", "valor = round(valor)"),
 (R, "dólares sin decimales", 'f"{valor:,.2f}"', 'f"{valor:,.0f}"'),
 (R, "sin aviso del último dato", "los datos del modelo llegan hasta el {fecha_en_texto(ultimo)} y no conoce el precio actual; ", ""),
 (R, "sin aviso de que la ventaja es la deriva", "en las pruebas su ventaja sobre repetir el último precio vino solo del crecimiento medio histórico y no de las variables que usa, ", ""),
 (R, "sin aviso de inversión", "una referencia y no una recomendación de inversión", "una referencia"),
 (R, "unidad en pesos", '"unidad": "USD"', '"unidad": "MXN"'),
 (R, "comandos de voz vacíos", '"comandos": ["precio de la accion", "bolsa", "sp500"],', '"comandos": [],'),
 (R, "meses desplazados", '"febrero", "marzo"', '"marzo", "febrero"'),
 (R, "intervalo invertido", "{dolares(valor / amplitud)} y {dolares(valor * amplitud)}", "{dolares(valor * amplitud)} y {dolares(valor / amplitud)}"),
 # --- serie (copia de la del modelo 01) ---
 (S, "ventana mínima de 30", "VENTANA_MINIMA = 31", "VENTANA_MINIMA = 30"),
 (S, "sin logaritmo en las características", "lc = np.log(c)\n    r = lc.diff()", "lc = c\n    r = lc.diff()"),
 (S, "ret_2 sin desplazar", '"ret_2": r.shift(1)', '"ret_2": r'),
 (S, "ret_7 con ventana 6", '"ret_7": lc - lc.shift(7)', '"ret_7": lc - lc.shift(6)'),
 (S, "media móvil de 7 con 6", "c.rolling(7).mean()", "c.rolling(6).mean()"),
 (S, "volatilidad poblacional", "r.rolling(30).std()", "r.rolling(30).std(ddof=0)"),
 (S, "ultima_fila: ret_3 mal indexado", '"ret_3": r[-3]', '"ret_3": r[-2]'),
 (S, "ultima_fila: ret_7 mal", "lc[-1] - lc[-8]", "lc[-1] - lc[-7]"),
 (S, "ultima_fila: media 30 con 29", "c[-30:].mean()", "c[-29:].mean()"),
 (S, "ultima_fila acepta historial corto", "if len(c) < VENTANA_MINIMA:", "if len(c) < 5:"),
 (S, "recursiva no realimenta la predicción", "historiales[i] = np.append(h, salida[i, paso])[-VENTANA_MINIMA:]", "historiales[i] = h"),
 (S, "recursiva usa suma en lugar de exp", "h[-1] * np.exp(retornos[i])", "h[-1] * (1 + retornos[i])"),
 (S, "recursiva parte de un cierre equivocado", "h[-1] * np.exp(retornos[i])", "h[-2] * np.exp(retornos[i])"),
 # --- train ---
 (T, "símbolos sin Google", 'SIMBOLOS = ["AAPL", "MSFT", "AMZN", "GOOGL"]', 'SIMBOLOS = ["AAPL", "MSFT", "AMZN"]'),
 (T, "fracción de prueba 0.3", "FRACCION_PRUEBA = 0.20", "FRACCION_PRUEBA = 0.30"),
 (T, "horizontes sin el 3", "HORIZONTES = (1, 3, 7)", "HORIZONTES = (1, 7)"),
 (T, "entrenamiento mira la prueba", "posicion <= corte - 2", "posicion <= corte"),
 (T, "prueba parte un día tarde", "posicion >= corte - 1", "posicion >= corte"),
 (T, "objetivo sin desplazar", ".diff().shift(-1)", ".diff()"),
 (T, "objetivo a dos días", ".diff().shift(-1)", ".diff().shift(-2)"),
 (T, "se mezclan los símbolos al construir", 'df.groupby("simbolo", sort=True):\n        cierres = g[OBJETIVO]', 'df.assign(simbolo="X").groupby("simbolo", sort=True):\n        cierres = g[OBJETIVO]'),
 (T, "sin ordenar por símbolo y fecha", '.sort_values(["simbolo", "fecha"])', ".sort_values([\"simbolo\"])"),
 (T, "retornos sin agrupar por símbolo", 'np.log(df[OBJETIVO]).groupby(df.simbolo).diff()', "np.log(df[OBJETIVO]).diff()"),
 (T, "persistencia con deriva", 'DummyRegressor(strategy="constant", constant=0.0)', 'DummyRegressor(strategy="mean")'),
 (T, "ridge sin escalar", 'RidgeCV(alphas=np.logspace(-1, 5, 25)), escalar=True)', 'RidgeCV(alphas=np.logspace(-1, 5, 25)), escalar=False)'),
 (T, "ridge con rejilla pequeña", "np.logspace(-1, 5, 25)", "np.logspace(-1, 1, 5)"),
 (T, "gradient boosting con parada temprana", "early_stopping=False, random_state=SEMILLA)),\n    }", "early_stopping=True, random_state=SEMILLA)),\n    }"),
 (T, "la selección puede elegir una línea base", "min((n for n in comparacion if not es_linea_base(n))", "min((n for n in comparacion"),
 (T, "ganador = el peor", "ganador = min((n for n in comparacion if not es_linea_base(n)), key=lambda n: comparacion[n][\"cv_rmse_retorno\"])", "ganador = max((n for n in comparacion if not es_linea_base(n)), key=lambda n: comparacion[n][\"cv_rmse_retorno\"])"),
 (T, "validación cruzada con 3 pliegues", "PLIEGUES_CV = 5", "PLIEGUES_CV = 3"),
 (T, "validación cruzada por filas sueltas", "cv=pliegues, scoring", "cv=PLIEGUES_CV, scoring"),
 (T, "pliegues sin agrupar por fecha", "np.isin(posicion, dias[entrena])", "np.isin(posicion, dias[entrena][::2])"),
 (T, "selección con la prueba", "cross_val_score(pipe, X_train, y_train,", "cross_val_score(pipe, X, y,"),
 (T, "sigma global en vez de por símbolo", 'sigma = {s: float(residuo.xs(s, level="simbolo").std(ddof=1)) for s in SIMBOLOS}', 'sigma = {s: float(residuo.std(ddof=1)) for s in SIMBOLOS}'),
 (T, "sigma con ddof=0", 'sigma = {s: float(residuo.xs(s, level="simbolo").std(ddof=1))', 'sigma = {s: float(residuo.xs(s, level="simbolo").std(ddof=0))'),
 (T, "sigma final igual a la del entrenamiento", '"sigma": {s: round(float(residuo_final.xs(s, level="simbolo").std(ddof=1)), 5) for s in SIMBOLOS}', '"sigma": {s: round(sigma[s], 5) for s in SIMBOLOS}'),
 (T, "modelo final solo con entrenamiento", "final = candidatos()[ganador].fit(X, y)", "final = candidatos()[ganador].fit(X_train, y_train)"),
 (T, "intervalo con 1.64", "np.exp(1.96 * sigma[s] * np.sqrt(h))", "np.exp(1.64 * sigma[s] * np.sqrt(h))"),
 (T, "intervalo sin raíz de h", "np.exp(1.96 * sigma[s] * np.sqrt(h))", "np.exp(1.96 * sigma[s])"),
 (T, "habilidad al revés", "return round(float(1 - np.sqrt(np.mean(np.square(e_modelo)) / np.mean(np.square(e_base)))), 4)", "return round(float(1 - np.sqrt(np.mean(np.square(e_base)) / np.mean(np.square(e_modelo)))), 4)"),
 (T, "habilidad contra la deriva con la persistencia", 'habilidad(rel["modelo"], rel["deriva"])', 'habilidad(rel["modelo"], rel["persistencia"])'),
 (T, "error relativo sin dividir por el real", "(y[s] - pred[nombre][s][:, columna]) / y[s]", "(y[s] - pred[nombre][s][:, columna])"),
 (T, "error con columna equivocada", "columna = h - 1\n        y = {", "columna = 0\n        y = {"),
 (T, "real del horizonte equivocado", "c[t + h] for h in range(1, MAX_HORIZONTE + 1)", "c[t + h] for h in range(0, MAX_HORIZONTE)"),
 (T, "orígenes sin recortar al horizonte máximo", "np.arange(corte - 1, n - MAX_HORIZONTE)", "np.arange(corte - 1, n - 1)"),
 (T, "historial incluye el futuro", "recursiva(p, [c[:t + 1] for t in origenes_prueba]", "recursiva(p, [c[:t + 2] for t in origenes_prueba]"),
 (T, "bootstrap sin bloques", "BLOQUE_BOOTSTRAP = 14", "BLOQUE_BOOTSTRAP = 1"),
 (T, "bootstrap con muy pocos remuestreos", "remuestreos: int = 1000", "remuestreos: int = 3"),
 (T, "autocorrelación sin centrar", "x = np.asarray(x, dtype=float) - np.mean(x)", "x = np.asarray(x, dtype=float)"),
 (T, "ejemplo de entrada distinto", '"entrada_ejemplo": {"simbolo": "AAPL", "dias_adelante": 1}', '"entrada_ejemplo": {"simbolo": "MSFT", "dias_adelante": 1}'),
 (T, "últimos cierres del inicio", "g[OBJETIVO].to_numpy()[-VENTANA_MINIMA:]", "g[OBJETIVO].to_numpy()[:VENTANA_MINIMA]"),
 (T, "fecha máxima del inicio", 'str(df.fecha.max().date())', 'str(df.fecha.min().date())'),
 (T, "acierto de dirección contra el destino", "(pred[\"modelo\"][s][:, columna] > partida[s]) == sube[s]", "(pred[\"modelo\"][s][:, columna] > y[s]) == sube[s]"),
 # --- añadidas tras la verificación del modelo 01 (mismos huecos) ---
 (R, "rango del 50 % en el texto", "con un rango del 95 % entre", "con un rango del 50 % entre"),
 (R, "punto estimado del texto duplicado", "cerraría alrededor de {dolares(valor)}", "cerraría alrededor de {dolares(valor * 2)}"),
 (T, "artefacto sin marca de reentrenado", "reentrenado_con_todo=True", "reentrenado_con_todo=False"),
 (T, "artefacto sin lista de símbolos", "simbolos=SIMBOLOS, ", ""),
 (T, "cobertura por mitad intercambiada", "d[:mitad].mean() for d in dentro.values()", "d[mitad:].mean() for d in dentro.values()"),
 # --- añadidas tras la verificación independiente del modelo 10 ---
 (R, "sin redondear la predicción", "valor = round(valor, 2)", "pass"),
 (R, "nombre de Amazon distinto", '"AMZN": "Amazon"', '"AMZN": "Amazon Inc"'),
 (R, "nombre de Google distinto", '"GOOGL": "Google"', '"GOOGL": "Alphabet"'),
 (R, "julio y agosto intercambiados", '"julio", "agosto"', '"agosto", "julio"'),
 (R, "sin ejemplo en dias_adelante", ", examples=[1]", ""),
 (R, "nombre del modelo distinto", '"nombre": "Predicción del precio de acciones del S&P 500"', '"nombre": "x"'),
 (T, "Fechas cuenta símbolos", "Fechas: {df.fecha.nunique()}", "Fechas: {df.simbolo.nunique()}"),
 (T, "Columnas cuenta filas", "Columnas: {df.shape[1]}", "Columnas: {df.shape[0]}"),
 (T, "autocorrelación de r² sin cuadrado", "autocorrelacion(ret[s].to_numpy() ** 2)", "autocorrelacion(ret[s].to_numpy())"),
 (T, "rezagos 2-6 impresos", "medio[:5]", "medio[1:6]"),
 (T, "cota 1.64", "cota = 1.96 / np.sqrt(len(ret))", "cota = 1.64 / np.sqrt(len(ret))"),
 (T, "autocorrelación con otro denominador", "/ np.sum(x ** 2) for k", "/ np.sum(x ** 2) * 2 for k"),
 (T, "main sin entender", "    entender(df)\n    corte = particion_temporal(df)", "    corte = particion_temporal(df)"),
]
