R, T, S = "router.py", "train.py", "serie.py"
M = [
 # --- router ---
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "mínimo de días 0", "Field(1, ge=1, le=MAX_DIAS", "Field(1, ge=0, le=MAX_DIAS"),
 (R, "máximo de días 8", "MAX_DIAS = 7", "MAX_DIAS = 8"),
 (R, "valor por defecto 2", "Field(1, ge=1", "Field(2, ge=1"),
 (R, "campo obligatorio", "Field(1, ge=1", "Field(..., ge=1"),
 (R, "z del intervalo 1.64", "Z95 = 1.96", "Z95 = 1.64"),
 (R, "intervalo crece lineal con los días", "np.sqrt(dias))", "dias)"),
 (R, "sin raíz en el intervalo", "np.sqrt(dias)", "1"),
 (R, "fecha destino = fecha del último dato", "destino = ultimo + timedelta(days=dias)", "destino = ultimo"),
 (R, "fecha destino con un día de más", "destino = ultimo + timedelta(days=dias)", "destino = ultimo + timedelta(days=dias + 1)"),
 (R, "predice un día menos", "artefacto[\"ultimos_cierres\"]], dias)[0, -1]", "artefacto[\"ultimos_cierres\"]], dias)[0, 0]"),
 (R, "predice siempre un día", "[artefacto[\"ultimos_cierres\"]], dias)", "[artefacto[\"ultimos_cierres\"]], 1)"),
 (R, "redondeo a enteros", "valor = round(valor, 2)", "valor = round(valor)"),
 (R, "sin aviso del último dato", "los datos del modelo llegan hasta el {fecha_en_texto(ultimo)} y no conoce el precio actual; ", ""),
 (R, "sin aviso de falta de habilidad", "en las pruebas no mejoró de forma demostrable a repetir el último precio conocido, así que es ", "es "),
 (R, "sin aviso de inversión", "una referencia y no una recomendación de inversión", "una referencia"),
 (R, "unidad en pesos", '"unidad": "USD"', '"unidad": "MXN"'),
 (R, "comandos de voz vacíos", '"comandos": ["precio del bitcoin", "bitcoin manana", "tipo de cambio del bitcoin"],', '"comandos": [],'),
 (R, "meses desplazados", '"julio", "agosto"', '"agosto", "julio"'),
 (R, "dólares con decimales", 'f"{valor:,.0f}"', 'f"{valor:,.1f}"'),
 (R, "intervalo invertido", "{dolares(valor / amplitud)} y {dolares(valor * amplitud)}", "{dolares(valor * amplitud)} y {dolares(valor / amplitud)}"),
 # --- serie ---
 (S, "ventana mínima de 30", "VENTANA_MINIMA = 31", "VENTANA_MINIMA = 30"),
 (S, "ventana mínima de 40", "VENTANA_MINIMA = 31", "VENTANA_MINIMA = 40"),
 (S, "sin logaritmo en las características", "lc = np.log(c)\n    r = lc.diff()", "lc = c\n    r = lc.diff()"),
 (S, "ret_2 sin desplazar", '"ret_2": r.shift(1)', '"ret_2": r'),
 (S, "ret_7 con ventana 6", '"ret_7": lc - lc.shift(7)', '"ret_7": lc - lc.shift(6)'),
 (S, "ret_30 con ventana 29", '"ret_30": lc - lc.shift(30)', '"ret_30": lc - lc.shift(29)'),
 (S, "media móvil de 7 con 6", "c.rolling(7).mean()", "c.rolling(6).mean()"),
 (S, "volatilidad con ventana 6", "vol_7\": r.rolling(7).std()", "vol_7\": r.rolling(6).std()"),
 (S, "volatilidad poblacional", "r.rolling(30).std()", "r.rolling(30).std(ddof=0)"),
 (S, "ultima_fila: ret_3 mal indexado", '"ret_3": r[-3]', '"ret_3": r[-2]'),
 (S, "ultima_fila: ret_7 mal", "lc[-1] - lc[-8]", "lc[-1] - lc[-7]"),
 (S, "ultima_fila: media 30 con 29", "c[-30:].mean()", "c[-29:].mean()"),
 (S, "ultima_fila: vol_30 poblacional", "r[-30:].std(ddof=1)", "r[-30:].std(ddof=0)"),
 (S, "ultima_fila acepta historial corto", "if len(c) < VENTANA_MINIMA:", "if len(c) < 5:"),
 (S, "recursiva no realimenta la predicción", "historiales[i] = np.append(h, salida[i, paso])[-VENTANA_MINIMA:]", "historiales[i] = h"),
 (S, "recursiva usa suma en lugar de exp", "h[-1] * np.exp(retornos[i])", "h[-1] * (1 + retornos[i])"),
 (S, "recursiva parte de un cierre equivocado", "h[-1] * np.exp(retornos[i])", "h[-2] * np.exp(retornos[i])"),
 (S, "recursiva sin recortar el historial", "np.append(h, salida[i, paso])[-VENTANA_MINIMA:]", "np.append(h, salida[i, paso])"),
 # --- train ---
 (T, "fracción de prueba 0.3", "FRACCION_PRUEBA = 0.20", "FRACCION_PRUEBA = 0.30"),
 (T, "horizontes sin el 3", "HORIZONTES = (1, 3, 7)", "HORIZONTES = (1, 7)"),
 (T, "partición de entrenamiento mira la prueba", "indice[indice <= corte - 2]", "indice[indice <= corte]"),
 (T, "prueba parte un día tarde", "indice[indice >= corte - 1]", "indice[indice >= corte]"),
 (T, "objetivo sin desplazar", ".diff().shift(-1)", ".diff()"),
 (T, "objetivo a dos días", ".diff().shift(-1)", ".diff().shift(-2)"),
 (T, "fecha mal interpretada (día/mes)", '"%b %d, %Y"', '"%b %Y, %d"'),
 (T, "sin ordenar por fecha", '.sort_values("fecha").reset_index(drop=True)', ".reset_index(drop=True)"),
 (T, "volumen con separadores sin limpiar", 'df["Volume"].str.replace(",", "")', 'df["Volume"]'),
 (T, "persistencia con deriva", 'DummyRegressor(strategy="constant", constant=0.0)', 'DummyRegressor(strategy="mean")'),
 (T, "ridge sin escalar", 'RidgeCV(alphas=np.logspace(-1, 5, 25)), escalar=True)', 'RidgeCV(alphas=np.logspace(-1, 5, 25)), escalar=False)'),
 (T, "ridge con rejilla pequeña", "np.logspace(-1, 5, 25)", "np.logspace(-1, 1, 5)"),
 (T, "gradient boosting con parada temprana", "early_stopping=False, random_state=SEMILLA)),\n    }", "early_stopping=True, random_state=SEMILLA)),\n    }"),
 (T, "la selección puede elegir una línea base", "min((n for n in comparacion if not es_linea_base(n))", "min((n for n in comparacion"),
 (T, "ganador = el peor", "ganador = min((n for n in comparacion if not es_linea_base(n)), key=lambda n: comparacion[n][\"cv_rmse_retorno\"])", "ganador = max((n for n in comparacion if not es_linea_base(n)), key=lambda n: comparacion[n][\"cv_rmse_retorno\"])"),
 (T, "validación cruzada con 3 pliegues", "PLIEGUES_CV = 5", "PLIEGUES_CV = 3"),
 (T, "validación cruzada aleatoria", "cv=TimeSeriesSplit(PLIEGUES_CV)", "cv=KFold(PLIEGUES_CV, shuffle=True, random_state=SEMILLA)"),
 (T, "selección con la prueba", "cross_val_score(pipe, X_train, y_train,", "cross_val_score(pipe, X, y,"),
 (T, "sigma con ddof=0", "np.std(y_train - pipeline.predict(X_train), ddof=1)", "np.std(y_train - pipeline.predict(X_train), ddof=0)"),
 (T, "sigma final con la prueba mal", "sigma_final = float(np.std(y - final.predict(X), ddof=1))", "sigma_final = sigma"),
 (T, "modelo final solo con entrenamiento", "final = candidatos()[ganador].fit(X, y)", "final = candidatos()[ganador].fit(X_train, y_train)"),
 (T, "intervalo con 1.64", "np.exp(-1.96 * sigma * np.sqrt(h))", "np.exp(-1.64 * sigma * np.sqrt(h))"),
 (T, "intervalo sin raíz de h", "np.exp(1.96 * sigma * np.sqrt(h))", "np.exp(1.96 * sigma)"),
 (T, "habilidad al revés", "1 - np.sqrt(np.mean(error[\"modelo\"] ** 2) / np.mean(error[\"persistencia\"] ** 2))", "1 - np.sqrt(np.mean(error[\"persistencia\"] ** 2) / np.mean(error[\"modelo\"] ** 2))"),
 (T, "habilidad contra la deriva", "np.mean(error[\"persistencia\"] ** 2))), 4)", "np.mean(error[\"deriva\"] ** 2))), 4)"),
 (T, "MAPE sin dividir por el real", "np.abs(y - p[:, columna]) / y)", "np.abs(y - p[:, columna]))"),
 (T, "acierto de dirección contra el último en lugar del origen", "pred[\"modelo\"][:, columna] > partida) == sube", "pred[\"modelo\"][:, columna] > y) == sube"),
 (T, "error con columna equivocada", "y, columna = real[:, h - 1], h - 1", "y, columna = real[:, h - 1], 0"),
 (T, "real del horizonte equivocado", "cierres[t + h] for h in range(1, MAX_HORIZONTE + 1)", "cierres[t + h] for h in range(0, MAX_HORIZONTE)"),
 (T, "orígenes sin recortar al horizonte máximo", "origenes_prueba = origenes_prueba[origenes_prueba + MAX_HORIZONTE <= len(cierres) - 1]", "pass"),
 (T, "historial incluye el futuro", "historiales = [cierres[:t + 1] for t in origenes_prueba]", "historiales = [cierres[:t + 2] for t in origenes_prueba]"),
 (T, "bootstrap sin bloques", "BLOQUE_BOOTSTRAP = 14", "BLOQUE_BOOTSTRAP = 1"),
 (T, "bootstrap con muy pocos remuestreos", "remuestreos: int = 1000", "remuestreos: int = 3"),
 (T, "autocorrelación sin centrar", "x = np.asarray(x, dtype=float) - np.mean(x)", "x = np.asarray(x, dtype=float)"),
 (T, "autocorrelación sin normalizar", "/ np.sum(x ** 2) for k", "for k"),
 (T, "ejemplo de entrada distinto", '"entrada_ejemplo": {"dias_adelante": 1}', '"entrada_ejemplo": {"dias_adelante": 2}'),
 (T, "últimos cierres del inicio", "cierres[-VENTANA_MINIMA:]", "cierres[:VENTANA_MINIMA]"),
 (T, "fecha máxima del inicio", 'str(df.fecha.iloc[-1].date())', 'str(df.fecha.iloc[0].date())'),
 # --- añadidas tras la verificación independiente ---
 (R, "rango del 50 % en el texto", "con un rango del 95 % entre", "con un rango del 50 % entre"),
 (R, "punto estimado del texto duplicado", "cerraría alrededor de {dolares(valor)}", "cerraría alrededor de {dolares(valor * 2)}"),
 (T, "artefacto sin marca de reentrenado", "reentrenado_con_todo=True", "reentrenado_con_todo=False"),
 (T, "cobertura por mitad intercambiada", "[round(float(np.mean(dentro[:mitad])), 4), round(float(np.mean(dentro[mitad:])), 4)]", "[round(float(np.mean(dentro[mitad:])), 4), round(float(np.mean(dentro[:mitad])), 4)]"),
]
