R, T = "router.py", "train.py"
M = [
 (R, "sin aviso de que no es un diagnóstico", "no es un diagnóstico y no reemplaza", "y no reemplaza"),
 (R, "sin aviso de puntajes no calibrados", "Los puntajes no son probabilidades calibradas. ", ""),
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "límite de edad ge=-5", "age: int = Field(ge=18,", "age: int = Field(ge=-5,"),
 (R, "límite AST le=4000", "ast: float = Field(ge=6, le=400,", "ast: float = Field(ge=6, le=4000,"),
 (R, "límite creatinina le=100000", "crea: float = Field(ge=5, le=1200,", "crea: float = Field(ge=5, le=100000,"),
 (R, "sin aviso de rango", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if False:"),
 (R, "puntaje mal calculado en el texto", "round(puntajes[c] * 100)", "round(puntajes[c] * 10)"),
 (R, "sin leyenda de donante", 'if clase == "donante" else "")', 'if False else "")'),
 (R, "clase distinta de la del modelo", "clase, puntajes = predecir_con_pipeline(", "_, puntajes = predecir_con_pipeline("),
 (T, "ORDEN de las clases invertido", 'ORDEN = ["donante", "hepatitis", "fibrosis", "cirrosis"]', 'ORDEN = ["cirrosis", "fibrosis", "hepatitis", "donante"]'),
 (T, "ENFERMEDAD sin hepatitis", 'ENFERMEDAD = ["hepatitis", "fibrosis", "cirrosis"]', 'ENFERMEDAD = ["fibrosis", "cirrosis"]'),
 (T, "F1 micro en lugar de macro", 'f1_score(y, pred, labels=ORDEN, average="macro", zero_division=0)', 'f1_score(y, pred, labels=ORDEN, average="micro", zero_division=0)'),
 (T, "especificidad mal calculada", '"especificidad": round(float((~pred[~real]).mean()), 4)', '"especificidad": round(float((pred[~real]).mean()), 4)'),
 (T, "se conserva la clase sospechosa", 'df = df[df["category"].isin(CLASES)].reset_index(drop=True)', 'df = df.reset_index(drop=True)\n    df["category"] = df["category"].replace({"0s=suspect Blood Donor": "0=Blood Donor"})'),
 (T, "LR sin ponderar", 'LogisticRegression(max_iter=5000, class_weight="balanced")),\n        "k vecinos"', 'LogisticRegression(max_iter=5000)),\n        "k vecinos"'),
 (T, "RF sin ponderar", 'class_weight="balanced_subsample", random_state=SEMILLA, n_jobs=-1), escalar=False),', 'random_state=SEMILLA, n_jobs=-1), escalar=False),'),
 (T, "imputación con la media", 'SimpleImputer(strategy="median")', 'SimpleImputer(strategy="mean")'),
 (T, "partición sin estratificar", "test_size=0.2, stratify=df[OBJETIVO], random_state=SEMILLA)", "test_size=0.2, random_state=SEMILLA)"),
 (T, "ganador = el peor", "ganador = max((n for n in comparacion", "ganador = min((n for n in comparacion"),
 (T, "rango de TODO el dataset", 'rango": {c: [float(X_train[c].min()), float(X_train[c].max())] for c in NUMERICAS}', 'rango": {c: [float(df[c].min()), float(df[c].max())] for c in NUMERICAS}'),
 (T, "bootstrap del F1 con la exactitud", '"f1_macro": intervalo_bootstrap(np.asarray(y_test), pred, f1_macro_de),', '"f1_macro": intervalo_bootstrap(np.asarray(y_test), pred, lambda y, p: float((y == p).mean())),'),
 (T, "predicciones fuera de muestra sin mezclar", "cv=StratifiedKFold(5, shuffle=True, random_state=SEMILLA))\n    metricas[\"oof_entrenamiento\"]", "cv=StratifiedKFold(5))\n    metricas[\"oof_entrenamiento\"]"),
 (T, "kNN con 1 vecino", "KNeighborsClassifier(n_neighbors=5,", "KNeighborsClassifier(n_neighbors=1,"),
 (T, "ajuste final con entrenamiento+prueba", "pipeline = candidatos()[ganador].fit(X_train, y_train)\n", "pipeline = candidatos()[ganador].fit(df[VARIABLES], df[OBJETIVO])\n"),
 (R, "la leyenda de donante aparece siempre", 'if clase == "donante" else "")', 'if True else "")'),
 (R, "el router modifica la edad", "datos = entrada.model_dump()", 'datos = {**entrada.model_dump(), "age": entrada.age + 1}'),
 (R, "puntajes en orden alfabético en el texto", 'for c in ORDEN)', 'for c in sorted(ORDEN))'),
 (R, "comandos de voz vacíos", '"comandos": ["tipo de hepatitis", "diagnostico de hepatitis", "estado del higado"],', '"comandos": [],'),
 (R, "nombre vacío", '"nombre": "Clasificación del estado hepático por hepatitis C",', '"nombre": "",'),
 (R, "límite bilirrubina le=450", "bil: float = Field(ge=1, le=300,", "bil: float = Field(ge=1, le=450,"),
 (R, "límite colinesterasa le=28", "che: float = Field(ge=1, le=20,", "che: float = Field(ge=1, le=28,"),
 (R, "límite colesterol ge=0.7", "chol: float = Field(ge=1, le=12,", "chol: float = Field(ge=0.7, le=12,"),
 (R, "límite GGT le=1100", "ggt: float = Field(ge=2.5, le=800,", "ggt: float = Field(ge=2.5, le=1100,"),
 (R, "límite proteínas ge=25", "prot: float = Field(ge=40, le=100,", "prot: float = Field(ge=25, le=100,"),
 (R, "límite ALP le=900", "alp: float = Field(ge=6, le=500,", "alp: float = Field(ge=6, le=900,"),
 (R, "estricto desactivado solo en che", "che: float = Field(ge=1, le=20,", "che: float = Field(strict=False, ge=1, le=20,"),
 (T, "ALP sale del modelo", 'LABORATORIO = ["alb", "alp", "alt",', 'LABORATORIO = ["alb", "alt",'),
 (T, "el sexo entra al modelo", "CATEGORICAS: list[str] = []", 'CATEGORICAS: list[str] = ["sex"]'),
 (T, "sensibilidad calculada como precisión", '"sensibilidad": round(float(pred[real].mean()), 4)', '"sensibilidad": round(float(real[pred].mean()), 4)'),
 (T, "sensibilidad y especificidad intercambiadas", '{"sensibilidad": round(float(pred[real].mean()), 4), "especificidad": round(float((~pred[~real]).mean()), 4)}', '{"especificidad": round(float(pred[real].mean()), 4), "sensibilidad": round(float((~pred[~real]).mean()), 4)}'),
 (T, "casos por clase de la prueba mal contados", "int((y_test == c).sum()) for c in ORDEN}", "int((y_train == c).sum()) for c in ORDEN}"),
 (T, "rango tomado de la prueba", 'rango": {c: [float(X_train[c].min()), float(X_train[c].max())] for c in NUMERICAS}', 'rango": {c: [float(X_test[c].min()), float(X_test[c].max())] for c in NUMERICAS}'),
 (T, "kNN con pesos uniformes", 'weights="distance"', 'weights="uniform"'),
 (T, "Random Forest más profundo", "min_samples_leaf=2, max_depth=8,", "min_samples_leaf=2, max_depth=12,"),
 (T, "el experimento del ALP sin relleno al azar", 'azar.loc[vacios, "alp"] = np.random.default_rng(SEMILLA).choice(train["alp"].dropna().to_numpy(), int(vacios.sum()))', 'azar.loc[vacios, "alp"] = train["alp"].median()'),
]
