R, T = "router.py", "train.py"
M = [
 (R, "sin mencionar la biopsia", "real se determina por biopsia y ", "real se determina y "),
 (R, "sin aviso de puntajes no calibrados", "Los puntajes no son probabilidades calibradas. ", ""),
 (R, "sin aviso de que no es un diagnóstico", "no es un diagnóstico: la etapa real", "la etapa real"),
 (R, "campos extra permitidos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="ignore", strict=True)'),
 (R, "tipos laxos", 'ConfigDict(extra="forbid", strict=True)', 'ConfigDict(extra="forbid")'),
 (R, "límite de edad le=1000", "age: float = Field(ge=18, le=100,", "age: float = Field(ge=18, le=1000,"),
 (R, "límite bilirrubina le=60", "bilirubin: float = Field(ge=0.1, le=40,", "bilirubin: float = Field(ge=0.1, le=60,"),
 (R, "límite colesterol le=3500", "cholesterol: float = Field(ge=100, le=2200,", "cholesterol: float = Field(ge=100, le=3500,"),
 (R, "límite albúmina ge=0.5", "albumin: float = Field(ge=1.5, le=5.5,", "albumin: float = Field(ge=0.5, le=5.5,"),
 (R, "límite cobre le=1200", "copper: float = Field(ge=3, le=800,", "copper: float = Field(ge=3, le=1200,"),
 (R, "límite fosfatasa le=30000", "alk_phos: float = Field(ge=200, le=18000,", "alk_phos: float = Field(ge=200, le=30000,"),
 (R, "límite SGOT le=900", "sgot: float = Field(ge=20, le=600,", "sgot: float = Field(ge=20, le=900,"),
 (R, "límite triglicéridos le=1300", "tryglicerides: float = Field(ge=25, le=800,", "tryglicerides: float = Field(ge=25, le=1300,"),
 (R, "límite plaquetas ge=10", "platelets: float = Field(ge=40, le=700,", "platelets: float = Field(ge=10, le=700,"),
 (R, "límite protrombina le=40", "prothrombin: float = Field(ge=7, le=22,", "prothrombin: float = Field(ge=7, le=40,"),
 (R, "sin aviso de rango", 'if fuera_de_rango(CARPETA, MODELO_INFO["slug"], datos):', "if False:"),
 (R, "sexo sin restricción", 'sex: Literal["F", "M"]', "sex: str"),
 (R, "edema acepta un valor más", 'edema: Literal["N", "S", "Y"]', 'edema: Literal["N", "S", "Y", "X"]'),
 (R, "puntaje mal calculado en el texto", "round(puntajes[str(e)] * 100)", "round(puntajes[str(e)] * 10)"),
 (R, "etapa desplazada en la respuesta", "prediccion=int(etapa),", "prediccion=int(etapa) + 1,"),
 (R, "el router modifica la edad", "datos = entrada.model_dump()", 'datos = {**entrada.model_dump(), "age": entrada.age + 1}'),
 (R, "etapas en orden inverso en el texto", "ETAPAS = (1, 2, 3, 4)", "ETAPAS = (4, 3, 2, 1)"),
 (R, "comandos de voz vacíos", '"comandos": ["etapa de cirrosis", "tipo de cirrosis", "estadio de la cirrosis"],', '"comandos": [],'),
 (T, "ORDEN de las etapas invertido", "ORDEN = [1, 2, 3, 4]", "ORDEN = [4, 3, 2, 1]"),
 (T, "edad sin convertir a años", 'df["age"] = df["age"] / 365.25', 'df["age"] = df["age"]'),
 (T, "N_Days entra al modelo", "VARIABLES = NUMERICAS + CATEGORICAS  #", 'VARIABLES = NUMERICAS + CATEGORICAS + ["n_days"]  #'),
 (T, "casos completos solo en las numéricas", "df.dropna(subset=VARIABLES).reset_index(drop=True)", "df.dropna(subset=NUMERICAS).reset_index(drop=True)"),
 (T, "partición sin estratificar", "test_size=0.2, stratify=completos[OBJETIVO], random_state=SEMILLA)", "test_size=0.2, random_state=SEMILLA)"),
 (T, "imputación con la media", 'SimpleImputer(strategy="median")', 'SimpleImputer(strategy="mean")'),
 (T, "LR sin ponderar", 'LogisticRegression(max_iter=5000, class_weight="balanced")),\n        "random forest"', 'LogisticRegression(max_iter=5000)),\n        "random forest"'),
 (T, "RF sin ponderar", 'class_weight="balanced_subsample", random_state=SEMILLA, n_jobs=-1), escalar=False),', 'random_state=SEMILLA, n_jobs=-1), escalar=False),'),
 (T, "ganador = el peor", "ganador = max((n for n in comparacion", "ganador = min((n for n in comparacion"),
 (T, "rango de TODO el dataset", 'rango": {c: [float(X_train[c].min()), float(X_train[c].max())] for c in NUMERICAS}', 'rango": {c: [float(df[c].min()), float(df[c].max())] for c in NUMERICAS}'),
 (T, "error absoluto con otra potencia", "np.abs(y - p).mean()", "(np.abs(y - p) ** 2).mean()"),
 (T, "'dentro de 1 etapa' con 2", '"dentro_de_1_etapa": round(float((np.abs(y - p) <= 1).mean()), 4)', '"dentro_de_1_etapa": round(float((np.abs(y - p) <= 2).mean()), 4)'),
 (T, "kappa lineal en lugar de cuadrático", 'cohen_kappa_score(y, p, weights="quadratic")), 4)}', 'cohen_kappa_score(y, p, weights="linear")), 4)}'),
 (T, "predicciones fuera de muestra sin mezclar", "cv=StratifiedKFold(5, shuffle=True, random_state=SEMILLA))\n    metricas[\"oof_entrenamiento\"]", "cv=StratifiedKFold(5))\n    metricas[\"oof_entrenamiento\"]"),
 (T, "ajuste final con entrenamiento+prueba", "pipeline = candidatos()[ganador].fit(X_train, y_train)\n", "pipeline = candidatos()[ganador].fit(completos[VARIABLES], completos[OBJETIVO])\n"),
 (T, "experimento sin pacientes incompletos", "incompletos = df[~df.index.isin(df.dropna(subset=VARIABLES).index)]", "incompletos = df.iloc[:0]"),
 (T, "F1 micro en lugar de macro", 'f1_score(y, pred, labels=ORDEN, average="macro", zero_division=0)', 'f1_score(y, pred, labels=ORDEN, average="micro", zero_division=0)'),
 (R, "SGOT en U/mL", 'description="SGOT/AST (U/L)"', 'description="SGOT/AST (U/mL)"'),
 (R, "plaquetas en miles por mL", 'description="Plaquetas (10³/µL, miles por microlitro)"', 'description="Plaquetas (miles por mL)"'),
 (R, "sin la frase de que puede equivocarse", "esta estimación puede equivocarse por una etapa o más.", "esta estimación es fiable."),
 (R, "sin response_model", "@router.post(\"/predecir\", response_model=RespuestaPrediccion)", "@router.post(\"/predecir\")"),
 (T, "entender con el bloque mal definido", 'bloque = df[df["ascites"].isna()]', 'bloque = df[df["ascites"].notna()]'),
 (T, "explorar sin la figura de etapas", 'guardar_figura(figuras, "etapas")', "pass"),
]
